---
- hosts: all
  become: true
  tasks:
    - name: Create Physical Volume on /dev/xvdh
      community.general.pvcreate:
        device: /dev/xvdh
    
    - name: Create Volume Group
      community.general.vgcreate:
        vg: vg_var
        pvs: /dev/xvdh
    
    - name: Create Logical Volume
      community.general.lvcreate:
        vg: vg_var
        lv: lv_var
        size: 100%VG
    
    - name: Format the logical volume with ext4
      ansible.builtin.filesystem:
        fstype: ext4
        dev: /dev/vg_var/lv_var
    
    - name: Mount the logical volume
      ansible.builtin.mount:
        path: /mnt/new_var
        src: /dev/vg_var/lv_var
        fstype: ext4
        state: mounted
